[package]
name = "design_pattern"
version = "0.1.0"
authors = ["r31oad3d <r31oad3d@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]

[[bin]]
name = "factory_pattern"
path = "src/creational_pattern/factory_pattern/main.rs"
